# Use root/example user/password credentials
version: '3.7'

services:
  php-apache-environment:
    container_name: php-apache
    build:
        context: ./PHPDockerfile
        dockerfile: Dockerfile
    depends_on:
        - db
    volumes:
        - ./app/src:/var/www/html/
    ports:
        - 80:80

  db:
    container_name: db
    image: mysql
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
        MYSQL_DATABASE: MYSQL_DATABASE
        MYSQL_USER: MYSQL_USER
        MYSQL_PASSWORD: MYSQL_PASSWORD
    ports:
        - "9906:3306"
    volumes:
        - mysqlDB_data:/var/lib/mysql
        - ./mysqldb:/docker-entrypoint-initdb.d 

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
        - '8080:80'
    restart: always
    environment:
        PMA_HOST: db
    depends_on:
        - db

volumes: 
  mysqlDB_data:

